In [1]:
from lgca import get_lgca
from lgca.helpers import *
import numpy as np
import matplotlib.pyplot as plt

timesteps = 10
dim = 5
dens = 1
birthrate = 1
lgca= get_lgca(ib=True, geometry='lin', interaction='inheritance',\
               density = dens, dims = dim, r_b = birthrate, variation = False)

death rate set to r_d =  0.02
standard deviation set to =  0.1


In [2]:
lgca.timeevo(timesteps, record=True)
%matplotlib notebook
#lgca.OLD_plot_prop_num_off()
#lgca.plot_prop_numoff()



props_t [{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]
tmax=11, l=5
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 0
node [1 2]
labs [1 2]
node [3 4]
labs [3 4]
node [5 6]
labs [5 6]
node [7 8]
labs [7 8]
node [ 9 10]
labs [ 9 10]
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 

Progress: [####----------------] 20.0% props_t [{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]
tmax=11, l=5
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 0
node [1 2]
labs [1 2]
node [3 4]
labs [3 4]
node [5 6]
labs [5 6]
node [7 8]
labs [7 8]
node [ 9 10]
labs [ 9

Progress: [########------------] 40.0% props_t [{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'num_off': [-99, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]
tmax=11, l=5
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

labs [ 1 10]
node [3 2]
labs [3 2]
node [5 4]
labs [5 4]
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 3
node [5 8]
labs [5 8]
node [ 7 10]
labs [ 7 10]
node [9 2]
labs [9 2]
node [1 4]
labs [1 4]
node [3 6]
labs [3 6]
numoffs [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep

Progress: [##############------] 70.0% props_t [{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5], 'num_off': [-99, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

node [3 4]
labs [3 4]
node [5 6]
labs [5 6]
node [7 8]
labs [7 8]
node [ 9 10]
labs [ 9 10]
numoffs [[0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 1
node [9 4]
labs [9 4]
node [1 6]
labs [1 6]
node [3 8]
labs [3 8]
node [ 5 10]
labs [ 5 10]
node [7 2]
labs [7 2]
numoffs [[0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.

numoffs [[0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 2
node [7 6]
labs [7 6]
node [9 8]
labs [9 8]
node [ 1 10]
labs [ 1 10]
node [3 2]
labs [3 2]
node [5 4]
labs [5 4]
numoffs [[0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
timestep 3
node [5 8]
labs [5 8]
node [ 7 10]
labs [ 7 10]
node [

In [3]:
print('maxlabel_init = ', lgca.maxlabel_init)
#lgca.plot_prop_spatial(prop = 'lab_m')
errors(lgca)
count_fam(lgca)

maxlabel_init =  10
---errors?---
inheritance label passen
len(props) passt
---genealogical research---
num [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
genealogical tree: [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
number of ancestors: 10
number of offsprings: 2
max family number is 1 with ancestor cell 1


1

In [4]:
print(lgca.props)

{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}


In [5]:
print(lgca.props_t)


[{'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1], 'num_off': [-99, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]}, {'r_b': [0.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'lab_m': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 1]

In [6]:
l = np.zeros(5)
for i in range (len(l)):
    print(i)

0
1
2
3
4
