In [3]:
import numpy as np

# base
### init
set bc
set dims
init coords
init nodes
set interaction
cell density
apply boundaries
### set r_int(r)
set interaction radius to r
initialise non border nodes
initialise coords
update dynamic fields
### set interaction
### set bc
### calc flux
### random reset
set nodes
apply boundaries 
updates dynamic fields
### time step
intreraction
apply boundaries
propagation
apply boundaries
update dynamic fields
### time evo
# ibbase
### init
rint = 1
props = {}
set bc
set dims
init coords
init nodes
set interaction
cell density
apply boundaries
### set interaction 
set interactions. If kappa is a single value then all are that value else set entire array
### update dynamic fields
occupied
density
### convert bool to ib. 
This might be helpful to convert alive cells to ib cells
### random reset
### time evo
### calc flux
einstein summation over velocity cells
### get prop
### calc prop mean
# LGCA 1D
### set dims
sets l, k, restchannelNo, 
### init coords
### proapagation
# IBLGCA 1D
### init nodes
if nodes in input set non zero nodes to input nodes
else random reset based on density



In [11]:
L = 5
N_channels = 3
initial_channel_population = 2
total_cells = initial_channel_population*N_channels*L
single_ch = [1]*initial_channel_population
occupied = np.array([[single_ch]*N_channels]*L, dtype = object)

In [12]:
print(occupied)
occupied.shape

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


(5, 3, 2)

In [13]:
occupied = occupied.astype(np.uint)
occupied[occupied > 0] = np.arange(1, 1+occupied.sum(), dtype=np.uint) 

In [14]:
occupied

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]], dtype=uint64)

In [31]:
def create_nodes(L, n_channels, channel_population):
    # returns an array of shape (L, n_channels, channel_population)
    occupied = np.array([[list([1]*channel_population)]*N_channels]*L, dtype = object)
    #occupied = occupied.astype(np.uint)
    occupied[occupied > 0] = np.arange(1, 1+occupied.sum(), dtype=object) 
    return occupied


In [32]:
nodes = create_nodes(4,3,5)
nodes

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45]],

       [[46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]], dtype=object)

In [33]:
nodes.shape

(4, 3, 5)

In [38]:
nodes[2][2].insert(4)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'